### ISSUE TITLE
有没有centos7.3的示例？

### ISSUE THREAD

**Issue by zeyuanpinghe** [takara9/vagrant-glusterfs#2]
装glusterfs居然用的是win，给的例子也是win。
鬼子你疯了吗？

**Comment by takara9** [comment]
I am sorry, I can not read/write chinese. so, I reply in english.

I can't provide the example for CentOS 7 due to I don't have a time to create CentOS version. but, Playbook for GlusterFs will be able to convert easly for CentOS version. 
Please try yourself.

**Comment by zeyuanpinghe** [comment]
@takara9 virboxとVagrantが必要なことはよく分かっているのではないでしょうか。centos7

**Comment by zeyuanpinghe** [comment]
ありがとう
